
/**
 * Service to handle image composition for Instagram templates
 */

export const createInstagramSlide = async (
  base64Image: string,
  text: string,
  slideIndex: number,
  totalSlides: number
): Promise<string> => {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return reject('Could not get canvas context');

    const img = new Image();
    img.onload = () => {
      // Instagram Standard Square Resolution
      const size = 1080;
      canvas.width = size;
      canvas.height = size;

      // 1. Draw Background Image
      ctx.drawImage(img, 0, 0, size, size);

      // 2. Draw Bottom Gradient for Text Readability
      const gradientHeight = size * 0.4;
      const gradient = ctx.createLinearGradient(0, size - gradientHeight, 0, size);
      gradient.addColorStop(0, 'rgba(0, 0, 0, 0)');
      gradient.addColorStop(1, 'rgba(0, 0, 0, 0.9)');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, size - gradientHeight, size, gradientHeight);

      // 3. Draw "Slide X of Y" Indicator
      ctx.fillStyle = 'rgba(255, 255, 255, 0.5)';
      ctx.font = 'bold 24px sans-serif';
      ctx.textAlign = 'right';
      ctx.fillText(`${slideIndex} / ${totalSlides}`, size - 50, 50);

      // 4. Draw Script Text
      ctx.fillStyle = 'white';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'bottom';
      
      // Font settings
      const fontSize = 38;
      ctx.font = `italic ${fontSize}px serif`;
      const lineHeight = fontSize * 1.4;
      const maxWidth = size - 100; // Padding
      const x = 50;
      const yStart = size - 60;

      // Simple Text Wrapping
      const words = text.replace(/^"|"$/g, '').split(' ');
      let line = '';
      let lines = [];

      for (let n = 0; n < words.length; n++) {
        let testLine = line + words[n] + ' ';
        let metrics = ctx.measureText(testLine);
        let testWidth = metrics.width;
        if (testWidth > maxWidth && n > 0) {
          lines.push(line);
          line = words[n] + ' ';
        } else {
          line = testLine;
        }
      }
      lines.push(line);

      // Draw lines from bottom up
      for (let i = lines.length - 1; i >= 0; i--) {
        ctx.fillText(lines[i], x, yStart - (lines.length - 1 - i) * lineHeight);
      }

      // 5. Add a subtle "Generated by AI" watermark
      ctx.fillStyle = 'rgba(255, 255, 255, 0.3)';
      ctx.font = '14px sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText('INSTASTORYBOARD AI', 50, 45);

      resolve(canvas.toDataURL('image/png'));
    };
    img.onerror = reject;
    img.src = base64Image;
  });
};
